package com.viettel.im.database.BO;

// Generated May 7, 2009 3:47:15 AM by Hibernate Tools 3.2.4.GA

/**
 * DepositDetailId generated by hbm2java
 */
public class DepositDetailId implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

	private long depositId;
	private long stockModelId;

	public DepositDetailId() {
	}

	public DepositDetailId(long depositId, long stockModelId) {
		this.depositId = depositId;
		this.stockModelId = stockModelId;
	}

	public long getDepositId() {
		return this.depositId;
	}

	public void setDepositId(long depositId) {
		this.depositId = depositId;
	}

	public long getStockModelId() {
		return this.stockModelId;
	}

	public void setStockModelId(long stockModelId) {
		this.stockModelId = stockModelId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DepositDetailId))
			return false;
		DepositDetailId castOther = (DepositDetailId) other;

		return (this.getDepositId() == castOther.getDepositId())
				&& (this.getStockModelId() == castOther.getStockModelId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getDepositId();
		result = 37 * result + (int) this.getStockModelId();
		return result;
	}

}
