package com.viettel.im.database.BO;
// Generated Mar 23, 2015 9:36:16 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SaleTransVipOtp generated by hbm2java
 */
public class SaleTransVipOtp  implements java.io.Serializable {


     private String msisdn;
     private String otp;
     private Date createDateOtp;

    public SaleTransVipOtp() {
    }

	
    public SaleTransVipOtp(String msisdn) {
        this.msisdn = msisdn;
    }
    public SaleTransVipOtp(String msisdn, String otp, Date createDateOtp) {
       this.msisdn = msisdn;
       this.otp = otp;
       this.createDateOtp = createDateOtp;
    }
   
    public String getMsisdn() {
        return this.msisdn;
    }
    
    public void setMsisdn(String msisdn) {
        this.msisdn = msisdn;
    }
    public String getOtp() {
        return this.otp;
    }
    
    public void setOtp(String otp) {
        this.otp = otp;
    }
    public Date getCreateDateOtp() {
        return this.createDateOtp;
    }
    
    public void setCreateDateOtp(Date createDateOtp) {
        this.createDateOtp = createDateOtp;
    }




}


