package com.viettel.im.database.BO;

// Generated May 7, 2009 3:47:15 AM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;

/**
 * DepositDetail generated by hbm2java
 */
public class DepositDetail implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

	private DepositDetailId id;
	private Long priceId;
	private String depositType;
	private Long quantity;
	private Double price;
	private Double amount;

	public DepositDetail() {
	}

	public DepositDetail(DepositDetailId id, Long priceId) {
		this.id = id;
		this.priceId = priceId;
	}

	public DepositDetail(DepositDetailId id, Long priceId, String depositType,
			Long quantity, Double price_1, Double amount) {
		this.id = id;
		this.priceId = priceId;
		this.depositType = depositType;
		this.quantity = quantity;
		this.price = price_1;
		this.amount = amount;
	}

	public DepositDetailId getId() {
		return this.id;
	}

	public void setId(DepositDetailId id) {
		this.id = id;
	}

    public Long getPriceId() {
        return priceId;
    }

    public void setPriceId(Long priceId) {
        this.priceId = priceId;
    }

	

	public String getDepositType() {
		return this.depositType;
	}

	public void setDepositType(String depositType) {
		this.depositType = depositType;
	}

	public Long getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Long quantity) {
		this.quantity = quantity;
	}

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

	

	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

}
