package com.viettel.im.database.BO;
// Generated Mar 26, 2009 10:16:28 AM by Hibernate Tools 3.2.1.GA



/**
 * ReasonGroup generated by hbm2java
 */
public class ReasonGroup implements java.io.Serializable {


     private Long reasonGroupId;
     private String reasonGroupCode;
     private String reasonGroupName;
     private Long status;
     private String description;

    public ReasonGroup() {
    }

	
    public ReasonGroup(Long reasonGroupId, String reasonGroupCode, String reasonGroupName, Long status) {
        this.reasonGroupId = reasonGroupId;
        this.reasonGroupCode = reasonGroupCode;
        this.reasonGroupName = reasonGroupName;
        this.status = status;
    }
    public ReasonGroup(Long reasonGroupId, String reasonGroupCode, String reasonGroupName, Long status, String description) {
       this.reasonGroupId = reasonGroupId;
       this.reasonGroupCode = reasonGroupCode;
       this.reasonGroupName = reasonGroupName;
       this.status = status;
       this.description = description;
    }
   
    public Long getReasonGroupId() {
        return this.reasonGroupId;
    }
    
    public void setReasonGroupId(Long reasonGroupId) {
        this.reasonGroupId = reasonGroupId;
    }
    public String getReasonGroupCode() {
        return this.reasonGroupCode;
    }
    
    public void setReasonGroupCode(String reasonGroupCode) {
        this.reasonGroupCode = reasonGroupCode;
    }
    public String getReasonGroupName() {
        return this.reasonGroupName;
    }
    
    public void setReasonGroupName(String reasonGroupName) {
        this.reasonGroupName = reasonGroupName;
    }
    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


