package com.viettel.im.database.BO;

// Generated Apr 18, 2009 4:44:15 AM by Hibernate Tools 3.2.4.GA
import java.math.BigDecimal;
import java.util.Date;

/**
 * ReceiptExpense generated by hbm2java//
 */
public class ReceiptExpense implements java.io.Serializable {

    private long receiptId;
    private long receiptType;
    private String receiptNo;
    private long shopId;
    private long staffId;
    private Long delivererStaffId;
    private Long delivererShopId;
    private String type;
    private Date receiptDate;
    private Long reasonId;
    private String payMethod;
    private Double amount;
    private String status;
    private String username;
    private Date createDatetime;
    private Date approverDate;
    private String deliverer;
    private String address;
    private String notes;
    private Long destroyStaffId;
    private Date destroyDate;
    private Long approverStaffId;
    private String own;
    private String debt;
    private BigDecimal telecomServiceId;
    private String serialCode;

    public ReceiptExpense() {
    }

    public ReceiptExpense(long receiptId, long receiptType,
            String receiptNo, long shopId, long staffId, String type,
            Date receiptDate, String payMethod, Double amount, String status,
            String username, Date createDatetime) {
        this.receiptId = receiptId;
        this.receiptType = receiptType;
        this.receiptNo = receiptNo;
        this.shopId = shopId;
        this.staffId = staffId;
        this.type = type;
        this.receiptDate = receiptDate;
        this.payMethod = payMethod;
        this.amount = amount;
        this.status = status;
        this.username = username;
        this.createDatetime = createDatetime;
    }

    public ReceiptExpense(long receiptId, long receiptType,
            String receiptNo, long shopId, long staffId, Long delivererStaffId,
            Long delivererShopId, String type, Date receiptDate, Long reasonId,
            String payMethod, Double amount, String status, String username,
            Date createDatetime, Date approverDate, String deliverer,
            String address, String notes, Long destroyStaffId,
            Date destroyDate, Long approverStaffId, String own, String debt,
            BigDecimal telecomServiceId) {
        this.receiptId = receiptId;
        this.receiptType = receiptType;
        this.receiptNo = receiptNo;
        this.shopId = shopId;
        this.staffId = staffId;
        this.delivererStaffId = delivererStaffId;
        this.delivererShopId = delivererShopId;
        this.type = type;
        this.receiptDate = receiptDate;
        this.reasonId = reasonId;
        this.payMethod = payMethod;
        this.amount = amount;
        this.status = status;
        this.username = username;
        this.createDatetime = createDatetime;
        this.approverDate = approverDate;
        this.deliverer = deliverer;
        this.address = address;
        this.notes = notes;
        this.destroyStaffId = destroyStaffId;
        this.destroyDate = destroyDate;
        this.approverStaffId = approverStaffId;
        this.own = own;
        this.debt = debt;
        this.telecomServiceId = telecomServiceId;
    }

    public String getSerialCode() {
        return serialCode;
    }

    public void setSerialCode(String serialCode) {
        this.serialCode = serialCode;
    }

    public long getReceiptId() {
        return this.receiptId;
    }

    public void setReceiptId(long receiptId) {
        this.receiptId = receiptId;
    }

    public long getReceiptType() {
        return this.receiptType;
    }

    public void setReceiptType(long receiptType) {
        this.receiptType = receiptType;
    }

    public String getReceiptNo() {
        return this.receiptNo;
    }

    public void setReceiptNo(String receiptNo) {
        this.receiptNo = receiptNo;
    }

    public long getShopId() {
        return this.shopId;
    }

    public void setShopId(long shopId) {
        this.shopId = shopId;
    }

    public long getStaffId() {
        return this.staffId;
    }

    public void setStaffId(long staffId) {
        this.staffId = staffId;
    }

    public Long getDelivererStaffId() {
        return this.delivererStaffId;
    }

    public void setDelivererStaffId(Long delivererStaffId) {
        this.delivererStaffId = delivererStaffId;
    }

    public Long getDelivererShopId() {
        return this.delivererShopId;
    }

    public void setDelivererShopId(Long delivererShopId) {
        this.delivererShopId = delivererShopId;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Date getReceiptDate() {
        return this.receiptDate;
    }

    public void setReceiptDate(Date receiptDate) {
        this.receiptDate = receiptDate;
    }

    public Long getReasonId() {
        return this.reasonId;
    }

    public void setReasonId(Long reasonId) {
        this.reasonId = reasonId;
    }

    public String getPayMethod() {
        return this.payMethod;
    }

    public void setPayMethod(String payMethod) {
        this.payMethod = payMethod;
    }

    public Double getAmount() {
        return this.amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Date getCreateDatetime() {
        return this.createDatetime;
    }

    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    public Date getApproverDate() {
        return this.approverDate;
    }

    public void setApproverDate(Date approverDate) {
        this.approverDate = approverDate;
    }

    public String getDeliverer() {
        return this.deliverer;
    }

    public void setDeliverer(String deliverer) {
        this.deliverer = deliverer;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getNotes() {
        return this.notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Long getDestroyStaffId() {
        return this.destroyStaffId;
    }

    public void setDestroyStaffId(Long destroyStaffId) {
        this.destroyStaffId = destroyStaffId;
    }

    public Date getDestroyDate() {
        return this.destroyDate;
    }

    public void setDestroyDate(Date destroyDate) {
        this.destroyDate = destroyDate;
    }

    public Long getApproverStaffId() {
        return this.approverStaffId;
    }

    public void setApproverStaffId(Long approverStaffId) {
        this.approverStaffId = approverStaffId;
    }

    public String getOwn() {
        return this.own;
    }

    public void setOwn(String own) {
        this.own = own;
    }

    public String getDebt() {
        return this.debt;
    }

    public void setDebt(String debt) {
        this.debt = debt;
    }

    public BigDecimal getTelecomServiceId() {
        return this.telecomServiceId;
    }

    public void setTelecomServiceId(BigDecimal telecomServiceId) {
        this.telecomServiceId = telecomServiceId;
    }
}
